### ISSUE TITLE
2016年度大会参加費申し込み

### ISSUE THREAD

**Issue by kattsun17** [SLP-KBIT/ETR2016#39]
振り込み金額 : 48,600円

振り込み先 : 
三菱東京UFJ銀行　京橋支店
　普通預金 2834287
　口座名義 一般社団法人 組込みシステム技術協会

振り込み期限 : 05.31(火)

先生が金曜日までにお金をくれるらしいので振り込むこと

**Comment by kattsun17** [comment]
@Yatsuku もも同伴すること

**Comment by kattsun17** [comment]
振り込みの注意 !! 

　＊発行手数料をご入金の際に振込み名義人を以下の仕様でご記入下さいますようご協力をお願い致します。
　　『参加費請求書番号（右上の番号）』+『お客様名（左上、請求書宛名 ((株)などを除く)）』

292
香川大学 工学部サークル SLP

**Comment by ghost** [comment]
振り込みしゅーりょー
