### ISSUE TITLE
技術教育2の申し込み

### ISSUE THREAD

**Issue by kattsun17** [SLP-KBIT/ETR2016#43]
06.18(土)開催の技術教育2の申し込み期限が、06.16(木)になっております。
- [ ] 参加者の決定
- [ ] 懇親会参加の検討
- [ ] 行事連絡
- [ ] 行事報告

を行って参加登録をお願いします。

[https://www.etrobo.jp/2016team/index.php](url)

---

ETロボコン2016 中四国地区参加チームの皆さま

いつもお世話になっております。
ETロボコン中四国地区実行委員の脇坂です。

6月18日(土)開催予定の「中四国地区 技術教育2」の申し込み
受付を開始しております。
「参加チーム専用ページ」よりお申し込みください。

https://www.etrobo.jp/2016team/index.php

福山会場、広島会場のいずれかを選択していただく
形となります。締切は6/16 23:59です。

何点か留意事項がございますので、必ず以下をお読みいただき
ますようお願いいたします。

【福山会場の方】
＊技術教育2の会場は「エフピコRiM 7F 福山市ものづくり交流館」
　ですので、お間違えの無いようお願いします。
　また、商業施設のため、
　10:00にならないと入館できませんので、ご注意ください。
   http://monodukuri-f.com/

【広島会場の方】
・会場に使用する講義室は、講義棟1階104室です。
　講義棟の位置については、
　http://www.hiroshima-cu.ac.jp/page/content0005.html
　のキャンパスマップをご参照ください。

・会場の広島市立大学は、周辺に飲食店、コンビニ等の施設が
　ございません。恐れ入りますが、昼食は各自でご持参いただ
　きますようお願いいたします。

・駐車場を若干用意しております。
　希望される方は、本メーリングリスト宛にお問い合わせくだ
　さい。数に限りがありますので、ご希望に添えない場合はご
　了承ください。

【福山・広島共通】
・技術教育のテキストは参加チーム専用ページから各自ダウン
　ロードしてください（当日の配布は行いませんのでご注意
　ください）

・受付の開始が、10:00からとなっています。

----技術教育2　予定スケジュール----
10:00～        　受付
10:30～　　　  技術教育2（午前）
12:30～13:30　ランチミーティング
13:30～17:25　技術教育2（午後）
17:25～17:30　連絡事項等
18:00～20:00   懇親会

技術教育につきましては、今後も追加で連絡をさせていただく
予定でおります。配信されるメールには確実に目を通していた
だきますようお願いします。

**Comment by nagatsukey** [comment]
誰も行かないということなので閉じます
かっつんありがとう
