### ISSUE TITLE
[3pt] 倒立状態で直進を行う

### ISSUE THREAD

**Issue by nagatsukey** [SLP-KBIT/ETR2016#5]
### 概要

倒立振子APIを用いて2輪でバランスを取りながら直進するプログラムを作成する
### 完了条件
- [x] 倒立振子で姿勢を維持できる
- [x] 倒立振子しながら直進できる
- [x] 倒立振子しながら左右のモーターの誤差を計算しながら直進できる
### 締切

2016/06/01

**Comment by ghost** [comment]
Mission Complete.

**Comment by MaxMEllon** [comment]
refs : https://github.com/SLP-KBIT/ETR2016/commit/6ffd10c0d7844a8fa64917c6b79c859faf05c4c1
