### ISSUE TITLE
[3pt] ガレージの実装

### ISSUE THREAD

**Issue by nagatsukey** [SLP-KBIT/ETR2016#9]
### 概要

ガレージを攻略するプログラムを作成する
### 作業手順 (参考)
- [ ] 灰色から黒色に変わる瞬間を検出する
- [ ] 灰色と黒色の境目からガレージまで進む
### 完了条件
- [ ] ガレージを成功する

**Comment by MaxMEllon** [comment]
![2016-06-15 20 31 13](https://cloud.githubusercontent.com/assets/9594376/16078160/2c632dc2-3338-11e6-9d45-27eca66bf492.png)
